
$dir = dirname(__FILE__).'\bd.sql';
$frase = `caralho 'essa' merda porra asudhasudhasiuhdashdiauhd`;
$create = "CREATE TABLE 'administradoras' ( 'id' int(11) NOT NULL COMMENT '{\"label\": \"Ações\", \"ver\": \"true\", \"form\": \"false\", \"type\": \"acoes\"}', 'nome' varchar(60) NOT NULL COMMENT '{\"ver\": \"true\", \"form\": \"true\"}', 'alteracoes' text NOT NULL COMMENT '{\"ver\": \"false\", \"add\": \"false\", \"edt\": \"false\"}', 'situacao' varchar(8) NOT NULL COMMENT '{\"ver\": \"false\", \"add\": \"false\", \"edt\": \"false\"}' ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='{\"labelBrowser\": \"Administradoras\", \"labelForm\": \"Administradora\"}' ROW_FORMAT=COMPACT;";
$dados = `INSERT INTO 'administradoras' ('id', 'nome', 'alteracoes', 'situacao') VALUES (1, 'SumUp', 'Admin - 201.37.160.93 - 07/05/2019 20:23:23 - CADASTRO', 'ativo'), (2, 'Getnet', 'Anurag - 201.37.160.93 - 07/05/2019 22:16:16 - CADASTRO | Anurag - 201.37.160.93 - 07/05/2019 22:18:28 - ALTERAÇÃO >> {CRIOU A BANDEIRA de () para (Elo)}{ELO - TAXA DE RECEBIMENTO NO DÉBITO de () para (2%)}{ELO - DIAS DE RECEBIMENTO NO DÉBITO de () para (2)}{ELO - TAXA RECEBIMENTO CRÉDITO C/ JUROS de () para (15%)}{ELO - DIAS RECEBIMENTO CRÉDITO C/ JUROS de () para (30)}{ELO - DIAS RECEBIMENTO ANTECIPAÇÃO de () para (2)}{ELO - NÚMERO MÁXIMO PARCELAS de () para (6)}{ELO - TAXA DE RECEBIMENTO COM ANTECIPAÇÃO 1X de () para (2%)}{ELO - TAXA DE RECEBIMENTO NO CRÉDITO SEM JUROS 1X de () para (1%)}{ELO - TAXA DE RECEBIMENTO COM ANTECIPAÇÃO 2X de () para (4%)}{ELO - TAXA DE RECEBIMENTO NO CRÉDITO SEM JUROS 2X de () para (2%)}{ELO - TAXA DE RECEBIMENTO COM ANTECIPAÇÃO 3X de () para (6%)}{ELO - TAXA DE RECEBIMENTO NO CRÉDITO SEM JUROS 3X de () para (3%)}{ELO - TAXA DE RECEBIMENTO COM ANTECIPAÇÃO 4X de () para (8%)}{ELO - TAXA DE RECEBIMENTO NO CRÉDITO SEM JUROS 4X de () para (4%)}{ELO - TAXA DE RECEBIMENTO COM ANTECIPAÇÃO 5X de () para (10%)}{ELO - TAXA DE RECEBIMENTO NO CRÉDITO SEM JUROS 5X de () para (5%)}{ELO - TAXA DE RECEBIMENTO COM ANTECIPAÇÃO 6X de () para (12%)}{ELO - TAXA DE RECEBIMENTO NO CRÉDITO SEM JUROS 6X de () para (6%)} | Admin - 143.54.23.14 - 08/05/2019 09:29:18 - ALTERAÇÃO >> {ELO - TAXA DE RECEBIMENTO NO DÉBITO de (2%) para (3%)}{ELO - DIAS DE RECEBIMENTO NO DÉBITO de (2) para (0)}{ELO - TAXA RECEBIMENTO CRÉDITO C/ JUROS de (15%) para (5%)}{ELO - DIAS RECEBIMENTO ANTECIPAÇÃO de (2) para (1)}', 'ativo');`;
// echo $create; exit;
file_put_contents($dir, $create, FILE_TEXT);

exit;

CREATE TABLE 'administradoras2' ( 'id' int(11) NOT NULL COMMENT '{"label": "Ações", "ver": "true", "form": "false", "type": "acoes"}', 'nome' varchar(60) NOT NULL COMMENT '{"ver": "true", "form": "true"}', 'alteracoes' text NOT NULL COMMENT '{"ver": "false", "add": "false", "edt": "false"}', 'situacao' varchar(8) NOT NULL COMMENT '{"ver": "false", "add": "false", "edt": "false"}' ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='{"labelBrowser": "Administradoras", "labelForm": "Administradora"}' ROW_FORMAT=COMPACT;